# Generated by Django 4.1.2 on 2022-10-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cached_articles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cachedjobarticle", old_name="article_id", new_name="article",
        ),
        migrations.RenameField(
            model_name="cachedjobarticle", old_name="user_id", new_name="user",
        ),
        migrations.RenameField(
            model_name="cachednewsarticle", old_name="article_id", new_name="article",
        ),
        migrations.RenameField(
            model_name="cachednewsarticle", old_name="user_id", new_name="user",
        ),
    ]
