# Generated by Django 4.1.2 on 2022-10-17 18:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_jobarticle_author"),
        ("news", "0004_alter_newsarticle_time_added"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cached_articles", "0002_rename_article_id_cachedjobarticle_article_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cachedjobarticle", unique_together={("user", "article")},
        ),
        migrations.AlterUniqueTogether(
            name="cachednewsarticle", unique_together={("user", "article")},
        ),
    ]
