# Generated by Django 4.1.2 on 2022-10-17 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="time_added",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 10, 17, 11, 3, 16, 186727, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
