# Generated by Django 4.1.2 on 2022-10-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_newsarticle_time_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="time_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
