# Generated by Django 4.1.1 on 2022-10-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_newsarticle_time_utc"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsarticle", old_name="author", new_name="post_by",
        ),
    ]
