# Generated by Django 4.1.1 on 2022-10-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_newsarticle_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="api_time",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
