# Generated by Django 4.1.2 on 2022-10-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_alter_newsarticle_api_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsarticle", old_name="time_utc", new_name="time_added",
        ),
    ]
