# Generated by Django 4.1.2 on 2022-10-13 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_id", models.IntegerField(unique=True)),
                ("api_time", models.IntegerField()),
                ("author", models.CharField(max_length=100)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("title", models.CharField(max_length=200)),
                ("url", models.URLField(blank=True, null=True)),
                ("time_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
