# Generated by Django 4.1.2 on 2022-10-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobarticle", old_name="author", new_name="post_by",
        ),
        migrations.AlterField(
            model_name="jobarticle",
            name="time_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
