# Generated by Django 4.1.1 on 2022-10-01 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_rename_time_jobarticle_api_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobarticle",
            name="time_utc",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
