# Generated by Django 4.1.1 on 2022-10-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_jobarticle_time_utc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobarticle",
            name="type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="jobarticle",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
