# Generated by Django 4.1.2 on 2022-10-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_alter_jobarticle_type_alter_jobarticle_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobarticle", old_name="time_utc", new_name="time_added",
        ),
    ]
